### PR TITLE
Add Ecto 2 Compatibility

### PR DESCRIPTION
**Pull request by mootpointer**
**This is designed to be merged AFTER #3 is merged. It includes commits from that branch**

Building on previous changes, this follows interface changes in the
`Ecto.Changeset` API, most notably the changes to
`Ecto.Changeset.cast/3` and the move from `model` to `data` within the
changeset struct.

We've also set up things so we use the happy test connection pooling.

### CODE REVIEW

**Comment by denisw** [comment]
What is the status here? Will this be merged now that Ecto 2.0 has been released?

**Comment by mootpointer** [comment]
@denisw Looking into it today. Do you have any thoughts on #5? I'm thinking I'll release an Ecto 2 version and then pretty quickly release the ranked version replacing the explicit integer stuff.

**Comment by joshsmith** [comment]
@mootpointer also wondering about the status of this.

**Comment by darrin-wortlehock** [comment]
@mootpointer: Any chance this will be merged soon?

**Comment by mootpointer** [comment]
Merged and published as `v0.1.2`

**Comment by joshsmith** [comment]
:tada:

**Pull request merged**
